# ??? ?? ???? ???? 5?? ~ 6?? ?? ??? ???? ? ??? ????? ???? ??
server:
  port: 0
spring:
  application:
    name: 2ST-SERVICE
eureka:

  instance:
    instance-id: ${spring.application.name}:${spring.instance.instance-id:${random.value}}
    # Eureka Server?? Service Registry? ????? ??
  client:
    fetch-registry: true
    # Eureka Server? ?? ????? ????? ??
    register-with-eureka: true
    # Eureka Server? ?? URL ??
    service-url:
      defaultZone: http://localhost:8761/eureka